version: '3'

services:
  bbb:
#    image: bbb-docker:latest
#    build: ../
    image: lendletseng/bbb-docker:latest
    ports:
      - "2080:80"
      - "2443:443"
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - ./nginx:/etc/nginx/additional_conf
    networks:
      default:
        ipv4_address: 10.0.0.2
  app:
    entrypoint: [bin/start]
    image: lendletseng/greenlight_yzu:latest
    container_name: greenlight_yzu
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    networks:
      default:
        ipv4_address: 10.0.0.3
# When using external logging
#    logging:
#      driver: $LOG_DRIVER
#      options:
#        syslog-address: $LOG_ADDRESS
#        tag: $LOG_TAG
    volumes:
      - ./log:/usr/src/app/log
      - ./storage:/usr/src/app/storage
      - ./nginx:/etc/nginx/additional_conf
# When using sqlite3 as the database
#      - ./db/production:/usr/src/app/db/production
# When using postgresql as the database
    links:
      - db
  db:
    image: postgres:9.5
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cdffec259e95a3a9
    networks:
      default:
        ipv4_address: 10.0.0.4
networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/24
         gateway: 10.0.0.1
